workdir: "../"

rule install:
  input:
    "requirements.txt"
  log:
    "install.log"
  threads: 1
  shell:
    """
    module --latest load Miniconda3
    conda create --name delphi python=3.11 --yes
    source $(conda info --base)/etc/profile.d/conda.sh
    conda activate delphi
    pip install --upgrade --user pip
    pip install --requirement {input} --user
    conda install pytorch numpy
    pip install --upgrade --user numpy
    """

rule train_demo:
  input:
    script = "train.py",
    parms = "config/train_delphi_demo.py"
  log:
    "train.log"
  threads: 1
  shell:
    "python {input.script} {input.parms} --device=cuda --out_dir=Delphi-2M"
