PATH = "../"
rule install:
  input:
    f"{PATH}requirements.txt"
  threads: 1
  shell:
    """
    conda create -n delphi python=3.11\
    conda activate delphi\
    pip install -r {input}\
    """

rule train:
  input:
    f"{PATH}train.py",
    f"{PATH}config/train_delphi_demo.py"
  shell:
    "python {input[0]} {input[1]} --device=cuda --out_dir=Delphi-2M"
