workdir: "../"

rule install:
  input:
    "requirements.txt"
  log:
    "install.log"
  threads: 1
  shell:
    """
    conda create -n delphi python=3.11
    conda activate delphi
    pip install -r {input}
    """

rule train:
  input:
    script = "train.py",
    parms = "config/train_delphi_demo.py"
  log:
    "train.log"
  shell:
    "python {input.script} {input.parms} --device=cuda --out_dir=Delphi-2M"
